name: Build Passes

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: publish plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          node-version: 'latest'
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: 'gradle'
      - name: update plugins.json
        working-directory: src/echo-tools
        run: node src/build-plugins-json.mjs
      - name: npm install
        run: ./gradlew npmInstall
      - name: build plugins
        run: ./gradlew buildPlugins
      - name: build
        run: ./gradlew npmBuild
