name: public docker

on:
  push:
    branches: ['main']

jobs:
  build:
    name: publish docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
          node-version: 'latest'
      - uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: "17"
          cache: 'gradle'
      - name: update plugins.json
        working-directory: src/echo-tools
        run: node src/build-plugins-json.mjs
      - name: npm install
        run: ./gradlew npmInstall
      - name: build projects
        run: ./gradlew npmBuild
      - name: build and publish docker
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 604080725100.dkr.ecr.us-east-1.amazonaws.com
          docker build -t sage .
          docker tag sage 604080725100.dkr.ecr.us-east-1.amazonaws.com/poestack-insightsx:latest
          docker push 604080725100.dkr.ecr.us-east-1.amazonaws.com/poestack-insightsx:latest

